// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Summary struct {
	ID        string `json:"id"`
	Input     string `json:"input"`
	Summary   string `json:"summary"`
	CreatedAt string `json:"createdAt"`
}
